
services:  
  minibox-api:
    container_name: minibox-api
    build:
      context: .
      dockerfile: Minibox.App.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__MainDbContext=Server=minibox-database,1433;Database=Minibox;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - minibox-network

  minibox-presentation-site:
    container_name: minibox-presentation-site
    build:
      context: .
      dockerfile: minibox-presentation/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - minibox-api
    networks:
      - minibox-network

networks:
  minibox-network:
    driver: bridge
